name: kids_game
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_tts: ^3.7.0
  assets_audio_player: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/
    - assets/audio/
    - assets/audio/farm/
    - assets/audio/forest/
    - assets/audio/jungle/
    - assets/audio/tropical/
    - assets/images/
    - assets/images/farm/
    - assets/images/forest/
    - assets/images/jungle/
    - assets/images/tropical/
  uses-material-design: true