name: kids_game
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  assets_audio_player: ^3.1.0
  image: ^4.1.3
  sqflite: ^2.3.0
  dotted_border: ^2.1.0
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  google_fonts: ^6.1.0
  url_launcher: ^6.0.20
  share_plus: ^7.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/
    - assets/audio/
    - assets/audio/farm/
    - assets/audio/forest/
    - assets/audio/tropical/
    - assets/images/
    - assets/images/puzzleImages/
    - assets/images/seasons/
    - assets/images/farm/
    - assets/images/forest/
    - assets/images/tropical/
  fonts:
    - family: Jungle Hope
      fonts:
        - asset: assets/fonts/Jungle Hope.ttf
    - family: Lovely Kids
      fonts:
        - asset: assets/fonts/Lovely Kids.ttf
    - family: Mansalva
      fonts:
        - asset: assets/fonts/Mansalva.ttf
    - family: Mynerve
      fonts:
        - asset: assets/fonts/Mynerve.ttf
  uses-material-design: true